syntax = "proto3";

option csharp_namespace = "Host.Grpc.Services.Employee";

import "Protos/import/boolresponse.proto";
import "Protos/import/emptyrequest.proto";

// Сущность Employee
message GrpcEmployee {
    string id = 1;
    string name = 2;
    int32 hourlyRate = 3;
}

// Ответ со списком
message GrpcEmployeesResponse {
    repeated GrpcEmployee employees = 1;
}

// Сервис
service GrpcEmployeeService {
    rpc EmployeesList(requests.EmptyRequest) returns (GrpcEmployeesResponse);

    rpc EmployeeAdd(GrpcEmployee) returns (responses.BoolResponse);
}
